### ISSUE TITLE
Create a direct route to the badging table and link it in the readme.

### ISSUE THREAD

**Issue by kaxada** [badging/badging#100]
The badged events have moved from https://github.com/badging/event-diversity-and-inclusion?tab=readme-ov-file#badges-granted-version-3 to https://badging.chaoss.community/event-badging. for this matter we need to put a link to the table but the frontend implementation has no direct link to the table which this issue seeks to solve

- create a direct link/route to the table in the codebase
- update the readme with the link

**Comment by danielmarv** [comment]
> The badged events have moved from https://github.com/badging/event-diversity-and-inclusion?tab=readme-ov-file#badges-granted-version-3 to https://badging.chaoss.community/event-badging. for this matter we need to put a link to the table but the frontend implementation has no direct link to the table which this issue seeks to solve
> 
> * create a direct link/route to the table in the codebase
> * update the readme with the link

I would like to take on this @kaxada

**Comment by danielmarv** [comment]
> The badged events have moved from https://github.com/badging/event-diversity-and-inclusion?tab=readme-ov-file#badges-granted-version-3 to https://badging.chaoss.community/event-badging. for this matter we need to put a link to the table but the frontend implementation has no direct link to the table which this issue seeks to solve
> 
> * create a direct link/route to the table in the codebase
> * update the readme with the link

I would like to take on this @kaxada

**Comment by adeyinkaoresanya** [comment]
Hi @danielmarv! Are you still interested in taking this up?

**Comment by danielmarv** [comment]
yes i can take it on
