### ISSUE TITLE
add project and badge counter to home page of website

### ISSUE THREAD

**Issue by kaxada** [badging/badging#101]
the change to be implemented is in the image below.

the count of the numbers will be pulled from the backend and a route will be created for that. for now the focus is on the design. (it should be responsive)

![image](https://github.com/badging/badging/assets/54111299/f2b91697-6e22-42a0-9983-0a8fa86d04ba)

**Comment by OgoNelson** [comment]
Ok @kaxada I have taken it up

**Comment by SylviaifyX** [comment]
@kaxada @OgoNelson would love to work on this too

**Comment by germonprez** [comment]
We had a talk in the DEI WG meeting on April 24 and identified a slightly more updated design

**Comment by LamiWilliams** [comment]
Here's the updated design

<img width="1440" alt="Badging Website Counter" src="https://github.com/badging/badging/assets/54284167/1f7adc92-68c7-4ce8-996c-893a3488eba1">

**Comment by danielmarv** [comment]
@LamiWilliams @kaxada 
i have updated the the ui for the project and badge counter
![c1](https://github.com/badging/badging/assets/103020028/a4d24c9e-8df4-4154-8280-cff1e8b701ab)
