### ISSUE TITLE
[DOC]: Improve clarity of the contribution guide

### ISSUE THREAD

**Issue by misspee007** [badging/badging#114]
**Description**

**Affected Documentation**
https://github.com/badging/badging/blob/main/CONTRIBUTING.md

**Suggested improvement**

- [ ] Add a screenshot [here](https://github.com/badging/badging/blob/eaa71700718ccf387d4ca09da3e7d90d8c3f2dde/CONTRIBUTING.md#how-to-contribute), showing the location of the button.
![image](https://github.com/user-attachments/assets/63413cd9-2fd2-4d1e-a652-150baf98dfb3)

- [ ] Provide more details on the [Code Style and Standards](https://github.com/badging/badging/blob/eaa71700718ccf387d4ca09da3e7d90d8c3f2dde/CONTRIBUTING.md#code-style-and-standards). You can describe the code style and standards, or if they are documented somewhere, include a link to the document.

- [ ] In the [Issue tracking](https://github.com/badging/badging/blob/eaa71700718ccf387d4ca09da3e7d90d8c3f2dde/CONTRIBUTING.md#issue-tracking) section, contributors are encouraged to get in touch with the project maintainers. Please, include more information on the maintainers, like their names and how they can be reached. Also, help correct the typo here "..please **contact get in touch** with the project maintainers.."
![image](https://github.com/user-attachments/assets/ff8b0408-b879-42a2-ae60-2b59b96fcd65)

**Additional Information**

Maintainers are listed in the [ReadMe.md](https://github.com/badging/badging?tab=readme-ov-file#acknowledgments)

**Comment by Poison-Iveey** [comment]
Hi, I would like to handle this, could I be assigned?

**Comment by misspee007** [comment]
> Hi, I would like to handle this, could I be assigned?

Hi. Yes, I will assign it to you now. If you need anything, please leave a comment here or reach out to me on Slack (Precious Abubakar). 
Thanks!

**Comment by Poison-Iveey** [comment]
Alright , thank you

**Comment by Poison-Iveey** [comment]
Hi, what do i do next after i make the changes?

**Comment by misspee007** [comment]
> Hi, what do i do next after i make the changes?

Please create a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#creating-the-pull-request) so that your changes can be reviewed and merged.

**Comment by Poison-Iveey** [comment]
I have made a pull request , kindly review it
