### ISSUE TITLE
[BUG] The contents of the Badging forms does not correspond with the newer content of the checklist on Badging 4.0.

### ISSUE THREAD

**Issue by adeyinkaoresanya** [badging/badging#137]
The contents of the badging form are outdated and do not correspond with the content of the badging 4.0 checklist. There is a need to update this

Refer to one of the latest issues on [ event-diversity-and-inclusion repo](https://github.com/badging/event-diversity-and-inclusion/issues)

**Comment by Giftea** [comment]
@adeyinkaoresanya Can this be assigned to me? Thanks

**Comment by adeyinkaoresanya** [comment]
> @adeyinkaoresanya Can this be assigned to me? Thanks

Sure!
