### ISSUE TITLE
Identified Issues with the Badging Site and Process

### ISSUE THREAD

**Issue by germonprez** [badging/badging#35]
Hi @Ruth-ikegah, @kaxada, and @iamkingsleey. Here are a few issues that I've been finding as I've been using the new site: 

1. If "communication transparency" is removed in the DEI.md file, the badge is still awarded. The scan is somehow not seeing that it is missing. 

2.  In the response congratulations email: 
        - **The following text MUST be removed as we are not providing this**: In the coming 3-4 days, we will share a supplemental report on your project's language inclusivity. This report will provide valuable insights into how inclusive your project's language is to diversw audiences. This report is only a supplement to your DEI Badge and has no impact on current or future badges. The report will only be sent to this email and can be used in any way that you see fit.
        - **This text MUST be changed to only say CHAOSS DEI Project Bronze Badge**: We are thrilled to inform you that your recent review submission of your Open Source Project has been recognized and rewarded an All In CHAOSS DEI Bronze badge.

3. If I try and click on “Apply for a Badge” when How it Works, DEI.md File, or DEI Badges is highlighted, it generates a 404 error. 

4. The Project Badging pages do not have the color background

**Comment by kaxada** [comment]
@germonprez created new issues for this to separate concerns. but everything has been captured.
