### ISSUE TITLE
change background for projects table

### ISSUE THREAD

**Issue by kaxada** [badging/badging#46]
the background of this projects table should be while because the text is in black. the screenshot I took doesn't have any projects under it though but the table headers can be used as reference. 

<img width="1489" alt="image" src="https://github.com/badging/badging/assets/54111299/ba334cb1-7ddc-4c08-a887-e192b3a3dd82">

**Comment by misspee007** [comment]
Hey @Ruth-ikegah, it looks like this was addressed
![image](https://github.com/badging/badging/assets/71160347/2ed512c0-667d-44ce-8c2d-8d3692a6ae98)

No I don't think it was. If you check you won't be able to see the project repository links, I think it might be a text color issue

**Comment by SylviaifyX** [comment]
@kaxada I want to contribute to this particular issue..

**Comment by kaxada** [comment]
oops @SylviaifyX I got this fixed along the way since it showed up in the priority list of cleanups we had to make before 29th Jan. let me create more issues and tag you along if the ones open are not favourable
