### ISSUE TITLE
make `/select-project/*` protected routes only accesible after auth

### ISSUE THREAD

**Issue by kaxada** [badging/badging#49]

**Comment by IsraelChidera** [comment]
Hi Kaxada, can I work on this?

**Comment by IsraelChidera** [comment]
Hi @kaxada

**Comment by kaxada** [comment]
Hello. Thanks for pinging me @IsraelChidera

**Comment by adeyinkaoresanya** [comment]
Hello @IsraelChidera Are you done working on this issue?

**Comment by IsraelChidera** [comment]
Hi @adeyinkaoresanya This issue has been worked on and merged since Feb. I guess @kaxada forgot to remove it. Kindly check the Badging Board

**Comment by adeyinkaoresanya** [comment]
> Hi @adeyinkaoresanya This issue has been worked on and merged since Feb. I guess @kaxada forgot to remove it. Kindly check the Badging Board

Alright, thanks! Closing the issue now
