### ISSUE TITLE
change the background of `https://badging.chaoss.community/project-badging` to be colored

### ISSUE THREAD

**Issue by kaxada** [badging/badging#52]

**Comment by misspee007** [comment]
Hey @Ruth-ikegah, just to clarify.. is the background supposed to look different from this?

![image](https://github.com/badging/badging/assets/71160347/567c9767-a054-4afc-b413-1fa28810b5fa)

**Comment by Ruth-ikegah** [comment]
> Hey @Ruth-ikegah, just to clarify.. is the background supposed to look different from this?
> 
> ![image](https://private-user-images.githubusercontent.com/71160347/297976960-567c9767-a054-4afc-b413-1fa28810b5fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NjE3NTAsIm5iZiI6MTcwNTY2MTQ1MCwicGF0aCI6Ii83MTE2MDM0Ny8yOTc5NzY5NjAtNTY3Yzk3NjctYTA1NC00YWZjLWI0MTMtMWZhMjg4MTBiNWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEwNTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNjYwMzMwNDhlNTRjZjllMWU1MDc4YmE0YjBkNjI3M2I4ZTRjNzkyNzQ4ODUyYTZkYWE1NDY5NjQ4NjY0YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1E6177XsgLF5FiZqLcLbPX0o-CWSL9r6S-1YJN1Ey6Q)

Hey @misspee007 if you check the other pages you will see that they have color at the bottom.

**Comment by misspee007** [comment]
> > Hey @Ruth-ikegah, just to clarify.. is the background supposed to look different from this?
> > ![image](https://private-user-images.githubusercontent.com/71160347/297976960-567c9767-a054-4afc-b413-1fa28810b5fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NjE3NTAsIm5iZiI6MTcwNTY2MTQ1MCwicGF0aCI6Ii83MTE2MDM0Ny8yOTc5NzY5NjAtNTY3Yzk3NjctYTA1NC00YWZjLWI0MTMtMWZhMjg4MTBiNWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEwNTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNjYwMzMwNDhlNTRjZjllMWU1MDc4YmE0YjBkNjI3M2I4ZTRjNzkyNzQ4ODUyYTZkYWE1NDY5NjQ4NjY0YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1E6177XsgLF5FiZqLcLbPX0o-CWSL9r6S-1YJN1Ey6Q)
> 
> Hey @misspee007 if you check the other pages you will see that they have color at the bottom.

I've seen it now, thanks
