### ISSUE TITLE
Enhance UI of repo dialog box

### ISSUE THREAD

**Issue by kaxada** [badging/badging#62]
There are three issues to sort out here
1. Enable scrolling of list of returned repos
currently the list of returned repositories is not scrollable which limits the number of repositories that are shown to the user. the intention is to modify the dialog box of returned screens so that the user is able to scroll through and select any repositories without even searching. 

2. Change the formatting of the repository names so that the returned strings look similar to repo URL. for example, instead of returning `GitLab Community / GitLab`, the list should return `gitlab-community/gitlab`. This in turn should affect the search implementation.
3. The search implementation/algorithm results should be based on alphabetical order. Meaning the first best match alphabetically should appear first and the rest follow in that hierarchy.

![image](https://github.com/badging/badging/assets/54111299/2d648b83-7bf6-44c9-92a4-429357c18df3)

**Comment by kaxada** [comment]
tagging @Teek-tech @sgoggins @dm-murphy to discuss the implementation and also follow up on the fixes here.

**Comment by dm-murphy** [comment]
> tagging @Teek-tech @sgoggins @dm-murphy to discuss the implementation and also follow up on the fixes here.

Thanks @kaxada tagging @zillemarco as well :-)

**Comment by dm-murphy** [comment]
> Change the formatting of the repository names so that the returned strings look similar to repo URL. for example, instead of returning GitLab Community / GitLab, the list should return gitlab-community/gitlab. This in turn should affect the search implementation.

@kaxada Just want to clarify the repo paths here:

For the main gitlab project (Marco and I don't have ownership rights to test) of GitLab.org / GitLab that would be `gitlab-org/gitlab`

For the community fork project (Marco and I do have ownership rights to test) of GitLab Community / GitLab Community fork that would be `gitlab-community/gitlab`

**Comment by zillemarco** [comment]
Thanks for the ping @dm-murphy 🙂 

@kaxada, I 💯 agree with all the points above to improve the UX. I think adding the scroll behavior could to be the simplest step to do at first, which could mitigate the other two issues with searching 🤔 

Let me know if you'd like me to have a look at anything 🙂

**Comment by kaxada** [comment]
@zillemarco I have not yet written any code on it. But if you would like to give it a go before I, @Teek-tech  or any other person does, I created a remote branch for it, you can get started and push small changes so that I can track that too and see where to add on. 

```sh
git fetch origin
git checkout enhance-search-implementation
```

**Comment by kaxada** [comment]
@dm-murphy please test this. I am happy to reopen the issue in case of new developments
