### ISSUE TITLE
Code Cleaning

### ISSUE THREAD

**Issue by kaxada** [badging/badging#71]
This issue is intended to clean up some aspects of the code. This issue focuses on;
- removing all the redundant code that was commented out

- commenting on the necessary code segments or lines

- change the casing  to match the following rules:
1. Variables and functions: CamelCase
2. Classes and constructors: PascalCase
3. Filenames, constants, and environment variables: Snake_case
4. HTML attributes and CSS class names: Kebab-case

While you are doing so, Please make sure your code never breaks in any way. Be sure to always be running the dev server

**Comment by kaxada** [comment]
@SylviaifyX here is a task for you. Please get it done in a week otherwise it will be unassigned and reassigned to someone else. 

Please reply to this comment so that I can assign it to you.

**Comment by SylviaifyX** [comment]
Ok thank.

**Comment by Ruth-ikegah** [comment]
Hi @SylviaifyX I just assigned the issue to you

**Comment by SylviaifyX** [comment]
@Ruth-ikegah @kaxada kindly review  my PR
