### ISSUE TITLE
[Project Badging Table]: Fix Search Feature and Table cells sizing

### ISSUE THREAD

**Issue by Teek-tech** [badging/badging#72]
- Fix search feature and filter on project badging page
- Resize table cells to align with the prototype
- Fix table responsiveness.

**Comment by kaxada** [comment]
@Teek-tech is this the issue you have been looking for?

**Comment by Teek-tech** [comment]
Yea, where did you find it? 😕 
I will jump on it right away. 💻

**Comment by adeyinkaoresanya** [comment]
hello @Teek-tech Are you done working on this issue?

**Comment by Teek-tech** [comment]
Yes. @adeyinkaoresanya

**Comment by adeyinkaoresanya** [comment]
> Yes. @adeyinkaoresanya

Okay! Thank you very much!
