### ISSUE TITLE
implement the `event badging` table

### ISSUE THREAD

**Issue by kaxada** [badging/badging#74]
we are looking to migrate the table at https://github.com/badging/event-diversity-and-inclusion/blob/main/README.md#badges-granted-version-3 to https://badging.chaoss.community/event-badging under badged events. 

The table design should be similar to https://badging.chaoss.community/project-badging `badged projects` table but having table columns of https://github.com/badging/event-diversity-and-inclusion/blob/main/README.md#badges-granted-version-3

**Comment by mide358** [comment]
@kaxada can you please point me to the API for the table at https://github.com/badging/event-diversity-and-inclusion/blob/main/README.md#badges-granted-version-3

**Comment by kaxada** [comment]
@mide358, @DesmondSanctity is getting that setup via https://github.com/badging/BadgingAPI/issues/25
