### ISSUE TITLE
Design the self-hosted projects' application form for the website

### ISSUE THREAD

**Issue by kaxada** [badging/badging#77]
we are looking to integrate an application into the website. This form is currently a Google form located [here](https://docs.google.com/forms/d/e/1FAIpQLSdoKt4K8L_LuuZ-0xaUd1ZL8JrIZ5dGt20XAFP7x2SfkAASdw/viewform). 

The goal is to use the fields in the form above to design a Figma webpage form that fits into the colours and design of https://badging.chaoss.community.

**Comment by kaxada** [comment]
related to https://github.com/badging/BadgingAPI/issues/12

**Comment by Kingscliq** [comment]
Hi @kaxada  has this been assigned, or is the design ready for development rather

**Comment by kaxada** [comment]
This was assigned to @LamiWilliams and I am sure she is almost done, or even done. @Kingscliq are you looking for design or coding issues?

**Comment by LamiWilliams** [comment]
Hi @kaxada @Kingscliq 
I've designed this. Here's a link: https://www.figma.com/file/BG3gSZL2ukRqtTz5i94CGH/Project-Badging?type=design&node-id=5154-10630&mode=dev

**Comment by Kingscliq** [comment]
> This was assigned to @LamiWilliams and I am sure she is almost done, or even done. @Kingscliq are you looking for design or coding issues?

Coding issues actually

**Comment by Kingscliq** [comment]
> Hi @kaxada @Kingscliq I've designed this. Here's a link: https://www.figma.com/file/BG3gSZL2ukRqtTz5i94CGH/Project-Badging?type=design&node-id=5154-10630&mode=dev

Ohh great, let me check this out

**Comment by Kingscliq** [comment]
Hi @kaxada  is there a backend for this already, also are there prebuilt components to manage the forms

**Comment by kaxada** [comment]
@Kingscliq I'll work on the endpoint ASAP and let you know. For the components, there are some that you will need to duplicate but since we have no form yet on our website I am sure components related to the form are to be built from scratch

**Comment by Kingscliq** [comment]
Hi @LamiWilliams pls send me a DM lets have a quick chat concerning the design, I just want to understand the flow and the direction, or we can start a thread on the **#chaossafrica-dev** channel

Name: Ajaezo Kingsley

**Comment by LamiWilliams** [comment]
> Hi @LamiWilliams pls send me a DM lets have a quick chat concerning the design, I just want to understand the flow and the direction, or we can start a thread on the **#chaossafrica-dev** channel
> 
> Name: Ajaezo Kingsley

Replying here so the convo can move back here:

The screens for the Event Badging application are arranged chronologically. It might help to see the [original form](https://chaoss.community/diversity-and-inclusion-badging/). Each sub-topic is on a new page on the design. Users can move forward and backward with the "Previous" and "Next" buttons. Also, the counter on the Next button just helps users know how long the form application is and where they currently are

The Project Badging application happens on one page

**Comment by Kingscliq** [comment]
> > Hi @LamiWilliams pls send me a DM lets have a quick chat concerning the design, I just want to understand the flow and the direction, or we can start a thread on the **#chaossafrica-dev** channel
> > Name: Ajaezo Kingsley
> 
> Replying here so the convo can move back here:
> 
> The screens for the Event Badging application are arranged chronologically. It might help to see the [original form](https://chaoss.community/diversity-and-inclusion-badging/). Each sub-topic is on a new page on the design. Users can move forward and backward with the "Previous" and "Next" buttons. Also, the counter on the Next button just helps users know how long the form application is and where they currently are
> 
> The Project Badging application happens on one page

Alright, so then is the data from the form going to one data source @kaxada  or will it be submitted independtly

**Comment by Kingscliq** [comment]
Hi @kaxada is there a format for creating branch names?

**Comment by adeyinkaoresanya** [comment]
@Kingscliq use your name hyphenated with a very short description of what you are working on

**Comment by Kingscliq** [comment]
> @Kingscliq use your name hyphenated with a very short description of what you are working on

Alight thanks @adeyinkaoresanya
