### ISSUE TITLE
Design the Event Badging form 

### ISSUE THREAD

**Issue by kaxada** [badging/badging#78]
If you look at the bottom of [this page](https://chaoss.community/diversity-and-inclusion-badging/), two form buttons are used to apply for either an in-person event or a virtual event. we want to move these forms to https://badging.chaoss.community/event-badging and they should be activated by the `apply for badge` option in the top right corner. This is to streamline the back-and-forth process and move everything to one website. 

[Here is the link to the Figma design](https://www.figma.com/file/BG3gSZL2ukRqtTz5i94CGH/Project-Badging?type=design&node-id=4418-6176&mode=design&t=7Xfu7GIyCnox5UTY-0) to consider for design consistency

**Comment by kaxada** [comment]
@LamiWilliams are you willing to take this up to?

**Comment by LamiWilliams** [comment]
Hi @kaxada Yes, I can work on this

**Comment by kaxada** [comment]
@LamiWilliams there you go

**Comment by Kingscliq** [comment]
Hi @kaxada @LamiWilliams, please let me know once the design is ready so I can hop on this

**Comment by LamiWilliams** [comment]
Hi @kaxada I've worked on this. Here's the link:https://www.figma.com/file/BG3gSZL2ukRqtTz5i94CGH/Project-Badging?type=design&node-id=5172-14887&mode=design&t=m9MsOhJlYgFrW0pq-4

**Comment by kaxada** [comment]
awesome. Thank you so much @LamiWilliams. we shall discuss this in our Wednesday DEI meeting and see the technical implementation

**Comment by mide358** [comment]
@kaxada I will also need the API's for the form submission. Thanks

**Comment by mide358** [comment]
Hello @kaxada  can you please point me to the API for the forms?
Thank you.
