### ISSUE TITLE
Fix mobile responsiveness

### ISSUE THREAD

**Issue by kaxada** [badging/badging#81]
When the website is opened in mobile view, you cannot access the header/navbar which is supposed to be like a hamburger menu in the top right corner. 
![WhatsApp Image 2024-02-11 at 18 53 04](https://github.com/badging/badging/assets/54111299/499977f3-8155-499f-b0f5-4912aa73c13f)

**Comment by IsraelChidera** [comment]
Hi. Will like to work on this

**Comment by daluclemas** [comment]
Hi Chidera, I am currently working on it. @IsraelChidera

**Comment by mihrab34** [comment]
anyone working on this? @adeyinkaoresanya @kaxada

**Comment by adeyinkaoresanya** [comment]
> anyone working on this? @adeyinkaoresanya @kaxada

@mihrab34 This has been fixed. Thank you for asking!
