### ISSUE TITLE
Build "In-Person Events" and "Virtual Events" Application forms

### ISSUE THREAD

**Issue by Ruth-ikegah** [badging/badging#82]
### **Current situation**

The application forms for both **in-person** and **virtual event** badging are currently located on a [separate website](https://chaoss.community/diversity-and-inclusion-badging/), causing users to navigate back and forth. 

### **Proposed Solution**
Integrate the application forms directly into the [badging website](https://badging.chaoss.community/event-badging). Users can access these forms through "Event Badging" under the "Apply for Badge" button located in the top right corner.

The design mockups for these integrated pages can be found [here]( https://www.figma.com/file/BG3gSZL2ukRqtTz5i94CGH/Project-Badging?type=design&node-id=5172-14887&mode=design&t=m9MsOhJlYgFrW0pq-4). This issue relates to #78

### **Benefits**
•  Streamlined User Experience: Users can seamlessly apply for badges without leaving the badging website, leading to a smoother and more engaging experience.
•  Enhanced Consistency: Integrating the forms aligns with the website's design and creates a more cohesive user journey.

**Comment by TemitopeAsama** [comment]
@adeyinkaoresanya I could take this on too

**Comment by adeyinkaoresanya** [comment]
@DesmondSanctity sending you a ping on this

**Comment by Giftea** [comment]
@adeyinkaoresanya Please assign me, thanks!

**Comment by DesmondSanctity** [comment]
@Giftea how's the UI refactoring going?

**Comment by adeyinkaoresanya** [comment]
> @Giftea how's the UI refactoring going? 
@DesmondSanctity she is done with it. We await pull request from you

**Comment by DesmondSanctity** [comment]
> > @Giftea how's the UI refactoring going? 
> @DesmondSanctity she is done with it. We await pull request from you
> 
> 

Alright. Will do that today.
