### ISSUE TITLE
Hamburger Icon for mobile screen.

### ISSUE THREAD

**Issue by daluclemas** [badging/badging#83]
![Screenshot (304)](https://github.com/badging/badging/assets/59066632/d4ee66ed-fd85-4d52-b54a-4e85ca2f7e65)

Add the hamburger icon for mobile screen and a mobile navigation menu.

**Comment by daluclemas** [comment]
@SylviaifyX

**Comment by SylviaifyX** [comment]
Noted @daluclemas
