### ISSUE TITLE
Modify or change `apply for badge` button

### ISSUE THREAD

**Issue by kaxada** [badging/badging#93]
the `apply for badge` button is the same when navigating the `Project Badging` or `Event Badging` Pages. This is confusing because if someone comes to the website with a motive of only applying they may end up clicking the wrong button since it is in the same location for both pages. the goal here is to strategize on where to place this badge.
<img width="1365" alt="image" src="https://github.com/badging/badging/assets/54111299/ae9dfc96-3bfc-4f8d-8852-c6913db9c752">

**Comment by kaxada** [comment]
@LamiWilliams can we see how to modify this?

**Comment by ElizabethN** [comment]
we talked about this in the DEI working group (thanks Adeyinka!) and we thought maybe a drop-down with 2 options might work? Just a thought! 😄

**Comment by OgoNelson** [comment]
I was in the DEI working group and I want to fix this issue

**Comment by LamiWilliams** [comment]
Sure @kaxada 
Thanks, @ElizabethN (and Adeyinka). I'll work with that

**Comment by LamiWilliams** [comment]
> I was in the DEI working group and I want to fix this issue

Oops, looks like we replied at the same time. Are you a designer? We can work on it together

**Comment by OgoNelson** [comment]
> > I was in the DEI working group and I want to fix this issue
> 
> Oops, looks like we replied at the same time. Are you a designer? We can work on it together

I am a developer, I want to effect the change  after the design team is done

**Comment by LamiWilliams** [comment]
> > > I was in the DEI working group and I want to fix this issue
> > 
> > 
> > Oops, looks like we replied at the same time. Are you a designer? We can work on it together
> 
> I am a developer, I want to effect the change after the design team is done

Oh, alright

**Comment by LamiWilliams** [comment]
@kaxada Please, find the design [here](https://www.figma.com/file/BG3gSZL2ukRqtTz5i94CGH/Project-Badging?type=design&node-id=5655-5301&mode=design&t=8TadsVnNjm5JqdIo-4)

With this new direction, it might be worth considering putting the "Apply for Badge" button on the landing page too; since users no longer need to go the Event Badging or Project Badging page before finding the button to apply for either of them

cc: @OgoNelson

**Comment by OgoNelson** [comment]
> @kaxada Please, find the design [here](https://www.figma.com/file/BG3gSZL2ukRqtTz5i94CGH/Project-Badging?type=design&node-id=5655-5301&mode=design&t=8TadsVnNjm5JqdIo-4)
> 
> With this new direction, it might be worth considering putting the "Apply for Badge" button on the landing page too; since users no longer need to go the Event Badging or Project Badging page before finding the button to apply for either of them
> 
> cc: @OgoNelson

Nice 👍, I agree with you, I think it's good that way

**Comment by kaxada** [comment]
@LamiWilliams the implementation is awesome. Thanks, @adeyinkaoresanya and @ElizabethN for the contribution and inputs. @OgoNelson please go ahead and create a PR for this. I am happy to merge this when it is ready

**Comment by OgoNelson** [comment]
> @LamiWilliams the implementation is awesome. Thanks, @adeyinkaoresanya and @ElizabethN for the contribution and inputs. @OgoNelson please go ahead and create a PR for this. I am happy to merge this when it is ready

Done and I have created a PR
