### ISSUE TITLE
Add "Become a Badger" option on the DEI Event badging page

### ISSUE THREAD

**Issue by ElizabethN** [badging/badging#96]
During the last Community Meeting, we decided that it would be great to add this option on the new Event Badging page to draw attention to the fact that anyone can become a Badger.

The text for the new page can read like this:

If you would like to help make open source events more inclusive and welcoming, becoming a Badger is a great way to do that! Badgers review incoming event badge applications and interact with the event organizers through GitHub. You do not need to have a deep knowledge of CHAOSS or the DEI metrics used in the application, so this is a perfect opportunity for those new to the community to begin contributing to CHAOSS right away. 

To learn more about becoming a Badger, join the [CHAOSS slack](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-28p56bayt-67TRjdA4yJWQmUd4hCzULg) and then join the #badging channel and let us know! We will point you in the right direction from there.

**Comment by danielmarv** [comment]
Please assign this to me

**Comment by OgoNelson** [comment]
> During the last Community Meeting, we decided that it would be great to add this option on the new Event Badging page to draw attention to the fact that anyone can become a Badger.
> 
> The text for the new page can read like this:
> 
> If you would like to help make open source events more inclusive and welcoming, becoming a Badger is a great way to do that! Badgers review incoming event badge applications and interact with the event organizers through GitHub. You do not need to have a deep knowledge of CHAOSS or the DEI metrics used in the application, so this is a perfect opportunity for those new to the community to begin contributing to CHAOSS right away.
> 
> To learn more about becoming a Badger, join the [CHAOSS slack](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-28p56bayt-67TRjdA4yJWQmUd4hCzULg) and then join the #badging channel and let us know! We will point you in the right direction from there.

Nice 👍 I was in the meeting.it is a good idea, I wanted to create the issue but couldn't come up with a good write up for the page, now that @ElizabethN  have provided the text for the page, I would love to implement the idea
